BR update by cleanbuild
- ERROR: Cannot find Cython: No module named Cython.Compiler.Version
- ERROR: cannot find a valid pkg-config package for ['gdk-x11-2.0']
- ERROR: cannot find a valid pkg-config package for ['libswscale']
- ERROR: cannot find a valid pkg-config package for ['pygobject-2.0']
- ERROR: cannot find a valid pkg-config package for ['x264']
- ERROR: cannot find a valid pkg-config package for ['xtst']
- wimpiggy/lowlevel/bindings.c:256:25: fatal error: pygtk/pygtk.h: No such file or directory